lib/commanded/assertions/event_assertions.ex
test/process_managers/process_manager_routing_test.exs
test/process_managers/resume_process_manager_test.exs
test/test_helper.exs

Then they can be used in user application tests

Move event assertions from tests to library

---

CHANGELOG.md
README.md
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
lib/commanded/process_managers/supervisor.ex
mix.exs
test/example_domain/money_transfer/transfer_money_process_manager.ex
test/process_managers/process_manager_instance_test.exs
test/process_managers/resume_process_manager_test.exs

Macro to assist with building process managers.

Process manager macro

---

README.md

I know it's obvious, but bring a little clarity.

Touch readme

---

CHANGELOG.md
guides/Commands.md
guides/Events.md
guides/Process Managers.md
guides/Read Model Projections.md
lib/commanded/commands/router.ex
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
test/commands/command_timeout_test.exs
test/event/event_handler_error_handling_test.exs
test/event/event_handler_macro_test.exs
test/event/handle_event_test.exs
test/example_domain/bank_account/account_balance_handler.ex
test/helpers/appending_event_handler.ex
test/process_managers/process_manager_error_handling_test.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/resume_process_manager_test.exs

Implements process manager error handling as described in #93.

Process manager command dispatch error handling

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/commands/routing_commands_test.exs

Add include_execution_result option to dispatch

---

guides/Aggregate Roots.md
guides/Commands.md
lib/commanded/assertions/event_assertions.ex
lib/commanded/event/handler.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/serialization/json_decoder.ex
test/aggregates/execute_command_for_aggregate_test.exs
test/helpers/wait.ex

First PR to start contributing on commanded!

Remove trailling spaces

---

CHANGELOG.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/supervisor.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/middleware/extract_aggregate_identity.ex
lib/commanded/middleware/pipeline.ex
test/aggregates/event_persistence_test.exs
test/commands/dispatch_consistency_test.exs

Prefix aggregate identity in command dispatch middleware

---

guides/Commands.md
guides/Events.md

Document metadata feature and note about serialization issues.

---

README.md

I also took the cheeky step of adding myself as a contributor :)

fix link to Greg Young's site.

---

.travis.yml
config/dev.exs
lib/commanded/process_managers/process_router.ex
test/commands/dispatch_consistency_test.exs
test/commands/support/consistency/consistency_aggregate_root.ex
test/commands/support/consistency/strongly_consistent_event_handler.ex
test/commands/support/consistency/strongly_consistent_process_manager.ex

Ensure process managers can be configured with `:strong` consistency

---

lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
test/process_managers/process_manager_routing_test.exs

Fix for the bug https://github.com/commanded/commanded/issues/25

Do not start new PM instance on :continue

---

lib/commanded/commands/router.ex

I don't think this PR needs a description :wink:

Fix typo in router option (fixed #208)

---

CHANGELOG.md
guides/Getting Started.md
guides/Serialization.md
lib/commanded/serialization/json_serializer.ex
mix.exs

Make poison an optional dependency

---

CHANGELOG.md
lib/commanded/aggregates/aggregate.ex
test/commands/command_timeout_test.exs

allow infinity timeout

---

guides/Commands.md

add documentation on how to prevent fields from being logged in debug mode

fix #169 - Update documentation on filtering field

---

guides/Testing.md

Adding some documentation on how to test an aggregate state.
fix #271 in the same way

feat(doc): add aggregate_state to testing's guide

---

lib/commanded/aggregates/aggregate.ex

It's possible for an Aggregate to receive an command before it's state
is initialized. This leads to execute/2 handlers receiving `nil` for the
aggregate state. It appears to happen more often when using a
distributed process registry. The fix is to replace the casts in the
init/1 handler with a chain of handle_continue/2 callbacks that are
guaranteed to complete before the first message is handled.
COMPATIBILITY NOTE: GenServer.handle_continue/2 requires OTP-21 or greater

Fix Aggregate initialization races

---

lib/commanded/middleware/logger.ex

Fix regression in `Commanded.Middleware.Logger.delta/1`.

---

guides/Events.md
lib/commanded/event/handler.ex
lib/mix/tasks/commanded.reset.ex
mix.exs
test/event/handle_event_test.exs
test/example_domain/bank_account/bank_account_handler.ex

Reset event handler

---

.travis.yml
CHANGELOG.md
guides/Application.md
guides/Choosing an Event Store.md
guides/Getting Started.md
guides/upgrades/0.19-1.0.md
lib/commanded/event_store.ex
mix.exs
mix.lock

Upgrade guide for v0.19 to v1.0.0-rc.0 and prepare release.

Prepare release v1.0.0-rc.0

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
test/aggregates/aggregate_lifespan_test.exs

address https://github.com/commanded/commanded/issues/279

Fix commanded aggregate race

---

.gitignore
bench/application/config_bench.exs
config/bench.exs
lib/commanded/application/config.ex
lib/commanded/application/supervisor.ex
mix.exs
mix.lock
test/application/application_test.exs
test/application/config_test.exs
test/event_store/support/subscriber.ex

Use application's name to lookup config directly, not by its PID.

Application config lookup

---

lib/commanded/pubsub/phoenix_pubsub.ex
mix.exs
mix.lock

Upgrades to phoenix_pubsub version 2.0
Uses the the child_spec API on Phoenix.PubSub
Addresses #364

Upgrade to phoenix_pubsub to 2.0

---

.formatter.exs

This was bugging me for awhile now :)

Add router/1 to locals_without_parens.

---

guides/Usage.md

Seems like there should be a comma here

Doc Fix - Add missing comma

---

guides/Supervision.md

Doc Fix - Add missing comma (2)

---

lib/commanded/process_managers/process_manager_instance.ex
test/process_managers/process_manager_error_handling_test.exs
test/process_managers/support/error/error_aggregate.ex
test/process_managers/support/error/error_handling_process_manager.ex

Capture exception on Process Manager apply/2 and call error/3 callback

---

lib/commanded/aggregates/aggregate.ex

Adds a `[:commanded, :aggregate, :execute, :exception]` event

Aggregate Telemetry Exceptions

---

lib/commanded/event/handler.ex

Remove superfluous stop event

---

.github/workflows/test.yml

My other PRs are failing on the elixir install. Hopefully updating will help

Update elixir version for github actions

---

lib/commanded/aggregates/default_lifespan.ex

Elixir introduced `@impl` to aid in the correct implementation of behaviours

chore: add @impl to DefaultLifespan

---

guides/Deployment.md

This one tripped me up - we had 4 event handlers and it took me a while before I remembered that the default for `:max_restarts` is really low :)

Small documentation change

---

lib/application.ex
lib/commanded.ex
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/aggregate_state_builder.ex
mix.exs
test/aggregates/aggregate_state_test.exs

This PR addresses https://github.com/commanded/commanded/issues/336

Get aggregate state

---

guides/Events.md

Adding doc to eventhandler on how it work internally

---

.tool-versions

Fixes a minor typo that blocks a fresh install

fix: asdf's erlang version

---

.tool-versions

Update erlang version

---

lib/commanded/process_managers/process_manager_instance.ex
test/process_managers/process_manager_instance_test.exs
test/support/mocks.ex

Use TypeProvider for process managers snapshot serialization

---

lib/commanded/commands/router.ex
test/application/telemetry_test.exs

fix(router.ex): Telemetry is not emitted if dispatch fails for {:error, :unregistered_command}

---

test/aggregates/aggregate_lifespan_test.exs

* Calculate time spent dispatching the commands and waiting to receive them. Reduce the time we'll flunk the test on if we hear a shutdown.
* Increase the test lifespan to account for... JIT? Some times the test takes longer than others... and more than 25 ms.

Account for time spent in lifespan test

---

.gitignore
.tool-versions

Upgrading the latest version `asdf` (devtool only), so we can take advantage of latest tooling

chore: remove asdf file

---

README.md

https://elixir-slackin.herokuapp.com is no longer working

update elixir slack link

---

lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/serialization/json_serializer.ex
lib/commanded/serialization/serializer.ex

Add generic serializer behaviour
