lib/commanded/aggregates/registry.ex
lib/commanded/event/handler.ex
test/aggregates/registry_test.exs

lets integer, atom or strings as aggregate_uuid in 
```
Commanded.Aggregates.Registry.open_aggregate(aggregate_module, aggregate_uuid)
```
using other values than string raising low level error on postgrex driver about text type

Support integer, atom or strings as aggregate_uuid in Commanded.Aggregates.Registry.open_aggregate(aggregate_module, aggregate_uuid)

---

README.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/handler.ex
lib/commanded/process_managers/process_manager.ex
mix.exs
mix.lock
test/aggregates/execute_command_for_aggregate_test.exs
test/commands/handle_command_test.exs
test/example_domain/bank_account/bank_account.ex
test/example_domain/money_transfer/money_transfer.ex
test/example_domain/money_transfer/transfer_money_process_manager.ex
test/process_managers/process_manager_test.exs
test/process_managers/resume_process_manager_test.exs

Don't persist an aggregate's pending events when executing a command returns an error.
An Aggregate should enforce domain rules by returning an error tuple instead of its state on failure. 
- An aggregate function must return `{:ok, aggregate}` on success.
- An aggregate function should return `{:error, reason}` on failure.
The example bank account aggregate returns `{:error, :account_already_open}` should an attempt be made to open an existing account.
```elixir
defmodule Commanded.ExampleDomain.BankAccount do
def open_account(%BankAccount{state: %{is_active?: true}} = account, %OpenAccount{}) do
{:error, :account_already_open}
end
def open_account(%BankAccount{state: %{is_active?: false}} = account, %OpenAccount{account_number: account_number, initial_balance: initial_balance}) when …
```

Don't persist an aggregate's pending events when executing a command returns an error

---

lib/commanded/aggregates/supervisor.ex

When we start a new aggregate, and kill it, supervisor immediately restart it with the last state, replaying all the events. But when sending a new Command to the same aggregate UUID, a new aggregate is created, and updated, so we end up with two aggregates on memory, one unusable (and consumed resources to be restarted) and a new fresh one, that was started by the last command request. Using :observer.start can help to track their state and see what is going on. Pls, let me know if you need more details to reproduce it.

Fix pending aggregates restarts: Supervisor restarts aggregate, that loses command routing and remains pending

---

CHANGELOG.md
README.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/handler.ex
lib/commanded/commands/router.ex
lib/commanded/middleware/logger.ex
lib/commanded/middleware/middleware.ex
lib/commanded/middleware/pipeline.ex
lib/commanded/supervisor.ex
mix.exs
test/commands/command_timeout_test.exs
test/helpers/command_audit_middleware.ex
test/helpers/commands/commands.ex
test/middleware/halting_middleware_test.exs
test/middleware/middleware_test.exs

Allow a command router to define middleware modules that are executed before and after success or failure of each command dispatch.
This provides an extension point to add in typical behaviour that you want to be called for every command the router dispatches command (e.g. validation, authorization, logging, etc.).
It follows, and is heavily inspired by, the [middleware approach taken by Exq](https://github.com/akira/exq#middleware-support).
```elixir
defmodule BankingRouter do
use Commanded.Commands.Router
middleware Commanded.Logger
middleware MyCommandValidator
middleware AuthorizeCommand
dispatch OpenAccount, to: OpenAccountHandler, aggregate: BankAccount, identity: :account_number
dispatch DepositMoney, to: DepositMoneyHandler, aggregate: BankAccount, identity: :account_number
end …
```

Command handling middleware

---

README.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
mix.exs
mix.lock
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/commands/command_timeout_test.exs
test/commands/handle_command_test.exs
test/commands/routing_commands_test.exs
test/event/handle_event_test.exs
test/example_domain/bank_account/bank_account.ex
test/example_domain/money_transfer/money_transfer.ex
test/example_domain/money_transfer/transfer_money_process_manager.ex
test/helpers/commands/commands.ex
test/middleware/middleware_test.exs
test/process_managers/process_manager_instance_test.exs
test/process_managers/process_manager_routing_test.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/resume_process_manager_test.exs

Drop `eventsourced` dependency.
Aggregate roots and process managers are now implemented using standard Elixir modules and functions, and structs for state. No external dependency requirements.
Aggregate root command functions receive its state and the command, returning any resultant domain events.
**Example aggregate root**
```elixir
defmodule BankAccount do
defstruct [account_number: nil, balance: nil]
def open_account(%BankAccount{} = account, account_number, initial_balance)
when initial_balance > 0
do
%BankAccountOpened{account_number: account_number, initial_balance: initial_balance}
end
def open_account(%BankAccount{} = account, account_number, initial_balance)
when initial_balance <= 0
do
{:error, :initial_balance_must_be_above_zero}
end
def apply(%BankAccount{} = account, …
```

Simplify aggregate roots and process managers

---

CHANGELOG.md
README.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
mix.exs
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/commands/routing_commands_test.exs
test/process_managers/resume_process_manager_test.exs

Command handlers should be optional to reduce boilerplate code. The default behaviour will be to configure a router to dispatch the command directly to its aggregate.
In your router you set the `to:` as the aggregate root itself. The `aggregate:` key is not required.
```elixir
defmodule ExampleRouter do
use Commanded.Commands.Router
dispatch OpenAccount, to: BankAccount, identity: :account_number
dispatch DepositMoney, to: BankAccount, identity: :account_number
end
``
By default the command will be dispatched to an aggregate root function named execute. Pattern matching will ensure that it invokes the correct function for a given command struct.
It is still be possible to configure a command handler as the `to:` target in your router when needed.

Command handlers should be optional by default 

---

CHANGELOG.md
README.md
config/dev.exs
config/test.exs
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_router.ex
mix.exs
mix.lock
test/event/handle_event_test.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/resume_process_manager_test.exs

Fixes #14.
When registering a new event handler or process manager the subscription it initially creates should be created from the position provided to the `start_link` function. This allows the user to determine which events it receives. By default this should be the origin position so that all events are received.
You can choose to start a subscription from the current event store position. Use this when you don't want newly created event handlers or process managers to go through all previous events (e.g. event handler to send transactional emails added to a deployed system).

Event handler and process manager subscriptions should be created from a given stream position 

---

.travis.yml
CHANGELOG.md
README.md
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
mix.lock
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/resume_process_manager_test.exs

Extend process manager `interested?/2` behaviour to support returning a `:stop` response. 
This will stop execution of an existing process instance, shutdown the process, and delete its persisted state from the event store.
```elixir
defmodule TransferMoneyProcessManager do
def interested?(%MoneyTransferRequested{transfer_uuid: transfer_uuid}), do: {:start, transfer_uuid}
def interested?(%MoneyWithdrawn{transfer_uuid: transfer_uuid}), do: {:continue, transfer_uuid}
def interested?(%MoneyDeposited{transfer_uuid: transfer_uuid}), do: {:continue, transfer_uuid}
def interested?(%MoneyTransferCompleted{transfer_uuid: transfer_uuid}), do: {:stop, transfer_uuid}
def interested?(_event), do: false
end
```

Stop process manager instance after reaching its final state 

---

lib/commanded/event/handler.ex

When you have nil in the metadata it fails because it's trying to
merge a nil with a map.

Fix having nil in metadata

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/aggregate_lifespan.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
test/aggregates/aggregate_lifespan_test.exs
test/commands/routing_commands_test.exs

I propose implementing the following behavior to manage aggregate lifetime. The main intention was that aggregate life controller should be separated entity from domain logic.
```elixir
defmodule ShopLifespan do
@behaviour Commanded.Aggregates.AggregateLifespan
def after_command(%StartShopWork{}), do: 3600 * 1000 * 8
def after_command(%StopShopWork{}), do: :hibernate
def after_command(%CloseShop{}), do: 0
end
```
It should be specified in router:
```elixir
defmodule CommandRouter do
use Commanded.Commands.Router
dispatch [
StartShopWork,
StopShopWork,
CloseShop,
], to: MyAggregate, lifespan: MyAggregateLifespan, identity: :aggregate_id
end
```

Shutdown idle aggregate processes.

---

CHANGELOG.md
README.md
lib/commanded/commands/handler.ex
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex
mix.exs
test/event/event_handler_macro_test.exs
test/example_domain/bank_router.ex
test/example_domain/money_transfer/transfer_money_process_manager.ex
test/process_managers/process_manager_routing_test.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/resume_process_manager_test.exs

`Commanded.Event.Handler` and `Commanded.ProcessManagers.ProcessManager` macros to simplify defining, and starting, event handlers and process managers.
Note the previous approach to defining and starting may still be used, so this is *not* a breaking change.
Release 0.12.0

Event handler and process manager macros

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/supervisor.ex
test/aggregates/aggregate_lifespan_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/helpers/process.ex

Gday @slashdotdash,
I'd like to use commanded across multiple nodes, the first step of which would be to be able to run it with a global process registry. This PR allows you to compile commanded using a registry provider other than `Registry` by specifying the module in config as `:registry_provider`. It will should work with any registry that supports `:via` tuples (thus the changes to the tests - `lookup` isn't one of the callbacks required to support them), while still compiling with `Registry` by default.
I was toying with the idea of writing a `Commanded.Registry.Provider` behaviour, with a default implementation using `Registry` as `Commanded.Registry` but this was the simpler option and I wanted to get feedback on the idea first.
I have a branch …

Allow compiling in other registry providers

---

CHANGELOG.md
README.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
mix.exs
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/commands/routing_commands_test.exs

You can optionally choose to include the aggregate's updated version as part of a command dispatch result by setting `include_aggregate_version` true:
```elixir
{:ok, aggregate_version} = BankRouter.dispatch(command, include_aggregate_version: true)
```
This is useful when you need to wait for an event handler (e.g. a read model projection) to be up-to-date before continuing or querying its data.
The default is to return only `:ok`, which is the same as before this change:
```elixir
:ok = BankRouter.dispatch(command)
```

Command dispatch optionally returns aggregate version

---

README.md

If you start it with only the keyword list, the application start stops with `        ** (FunctionClauseError) no function clause matching in Keyword.merge/2` because the keyword list is not the first argument but the whole list of arguments.

Adjust documentation to make Process Managers work

---

config/test.exs
guides/Commands.md
guides/Events.md
guides/Read Model Projections.md
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
lib/commanded/event/handler.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/event_store/event_store.ex
lib/commanded/event_store/recorded_event.ex
lib/commanded/middleware/consistency_guarantee.ex
lib/commanded/middleware/extract_aggregate_identity.ex
lib/commanded/middleware/pipeline.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_router.ex
lib/commanded/subscriptions/subscriptions.ex
lib/commanded/supervisor.ex
test/commands/command_timeout_test.exs
test/commands/dispatch_consistency_test.exs
test/commands/routing_commands_test.exs
test/subscriptions/subscriptions_test.exs

Add support for command dispatch that waits for all strongly consistent handlers (event handlers, process managers) to have successfully processed all events created by the command being dispatched. 
Created a `Subscriptions` module to track all event store subscriptions. It uses an ETS table to track subscriptions and streams/versions that have been handled per subscription. 
Added a  `consistency` option to event handlers, process managers, and command router. It supports either `:eventual` (default) or `:strong` consistency. 
Consistency is guaranteed by a new command dispatch middleware that blocks after successful dispatch. Once you receive an `:ok` reply from a command dispatch you are guaranteed that the handlers have completed. 
Fixes #82.

Command dispatch with strong consistency guarantee

---

CHANGELOG.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
lib/commanded/event_store/adapters/in_memory.ex
mix.exs
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/commands/routing_commands_test.exs
test/event_store_adapter/append_events_test.exs

Allow metadata to be provided when dispatching a command:
```elixir
command = %OpenAccount{account_number: "ACC123", initial_balance: 1_000}
metadata = %{"user_id" => "user-12345", "ip_address" => "127.0.0.1"}
:ok = BankRouter.dispatch(command, metadata: metdata)
```
The *optional* metadata is recorded against all events created by the command. This is useful for additional auditing purposes, such as recording the user's identity, their source IP address, etc.
Fixes #61.
Thanks to @sammkj for implementing this feature.

Include custom metadata during command dispatch

---

.travis.yml
CHANGELOG.md
lib/commanded/commands/router.ex
test/commands/routing_commands_test.exs

Ensure the command, handler, and aggregate modules exist when configured in a router module.
Fixes #59.

 Validate command dispatch registration in router

---

CHANGELOG.md
guides/Commands.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/supervisor.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
lib/commanded/middleware/extract_aggregate_identity.ex
test/aggregates/aggregate_lifespan_test.exs
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/aggregates/registry_test.exs
test/commands/routing_commands_test.exs
test/helpers/process.ex

Add support to command router to allow further specification of an aggregate identity and additionally an identity prefix.
1. Allow the aggregate identity prefix to be specified during command registration:
```elixir
defmodule BankRouter do
use Commanded.Commands.Router
dispatch [OpenAccount,DepositMoney,WithdrawMoney] 
to: BankAccount, 
identity: :account_number,
identity_prefix: "bank-account-"
end
```
2. Allow a function to be used as the `identity` option; you construct the identity as required from the command being dispatched:
```elixir
defmodule BankRouter do
use Commanded.Commands.Router
dispatch [RegisterUser] 
to: User, 
identity: fn %{uuid: uuid} -> "user-#{uuid}" end
dispatch [OpenAccount,DepositMoney,WithdrawMoney] 
to: BankAccount, 
identity: &BankRouter.account_identity/1 …
```

Additional stream prefix per aggregate

---

lib/commanded/process_managers/process_router.ex

A normal stop is already logged in `handle_event/2` with a debug level.

Remove unnecessary warning when a process managers stops itself

---

.travis.yml
lib/commanded/aggregates/aggregate.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/event/handler.ex
lib/commanded/middleware/consistency_guarantee.ex
lib/commanded/middleware/pipeline.ex
lib/commanded/subscriptions/subscriptions.ex
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_for_aggregate_test.exs
test/commands/dispatch_consistency_test.exs
test/subscriptions/subscriptions_test.exs

Commands that create no events don't require consistency checks.
Prevent blocking indefinitely when a strongly consistent event handler dispatches a command using `consistency: :strong`.

Ignore strong consistency check when command creates no events

---

lib/commanded/assertions/event_assertions.ex

`assert_receive_event` waits for an event of a specific type. But it
doesn't recognize if the given event type isn't valid, e.g. because it
hasn't been alias or has a typo. That way a test that should succeed
if the module had been aliased fails.
This change ensures the type is a known one or else raises an
assertion exception which indicates the fact.

Fail `assert_receive_event` if `event_type` isn't a known module

---

guides/Aggregate Roots.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/multi.ex
mix.exs
test/aggregates/multi_bank_account.ex
test/aggregates/multi_test.exs

Use `Commanded.Aggregate.Multi` to generate multiple events from a single command.
This can be useful when you want to emit multiple events that depend upon the aggregate state being updated.
In the example below, money is withdrawn from the bank account and the
updated balance is used to check whether the account is overdrawn.
```elixir
defmodule BankAccount do
defstruct [
account_number: nil,
balance: 0,
state: nil,
]
alias Commanded.Aggregate.Multi
def withdraw(
%BankAccount{state: :active} = account,
%WithdrawMoney{amount: amount})
when is_number(amount) and amount > 0
do
account
|> Multi.new()
|> Multi.execute(&withdraw_money(&1, amount))
|> Multi.execute(&check_balance/1)
end
def apply(%BankAccount{} = state, %MoneyWithdrawn{balance: balance}),
do: %BankAccount{state | balance: …
```

Add `Commanded.Aggregate.Multi`

---

lib/commanded/commands/dispatcher.ex
lib/commanded/middleware/pipeline.ex
test/middleware/middleware_test.exs

This is useful for middleware like [commanded-audit-middleware](https://github.com/commanded/commanded-audit-middleware/), which would be able to put the command uuid inside metadata automatically.

Let middlewares modify metadata before dispatch

---

CHANGELOG.md
README.md
guides/Choosing an Event Store.md
guides/Commands.md
guides/Read Model Projections.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
lib/commanded/event/handler.ex
lib/commanded/event/mapper.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/event_store/event_data.ex
lib/commanded/event_store/event_store.ex
lib/commanded/event_store/recorded_event.ex
lib/commanded/middleware/pipeline.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
mix.exs
test/commands/correlation_causation_test.exs
test/event/handle_event_test.exs
test/event_store_adapter/append_events_test.exs
test/example_domain/bank_router.ex
test/helpers/command_audit_middleware.ex
test/helpers/event_factory.ex
test/middleware/halting_middleware_test.exs
test/middleware/middleware_test.exs
test/test_helper.exs

To assist with monitoring and debugging your deployed application it is useful to track the causation and correlation ids for your commands and events.
- `causation_id` - the UUID of the command creating an event, or the event causing a command dispatch.
- `correlation_id` - a UUID used to correlate related commands/events.
This pull request allows you to set causation and correlation ids when dispatching a command:
```elixir
:ok = ExampleRouter.dispatch(command, causation_id: UUID.uuid4(), correlation_id: UUID.uuid4())
```
Commands dispatched by a process manager will be automatically assigned the appropriate causation and correlation ids from the source domain event.
Fixes #70.

Correlation and causation ids

---

lib/commanded/process_managers/supervisor.ex
lib/commanded/registration/local_registry.ex
lib/commanded/registration/registration.ex
lib/commanded/subscriptions/subscriptions.ex
lib/commanded/supervisor.ex
mix.exs
test/commands/correlation_causation_test.exs
test/commands/routing_commands_test.exs
test/commands/support/identity/identity_aggregate.ex
test/commands/support/identity/identity_aggregate_router.ex
test/commands/support/identity/identity_function_aggregate.ex
test/commands/support/identity/identity_function_router.ex
test/commands/support/open_account_bonus_handler.ex
test/event/event_handler_error_handling_test.exs
test/helpers/command_audit_middleware.ex
test/middleware/halting_middleware_test.exs
test/middleware/middleware_test.exs
test/process_managers/process_manager_error_handling_test.exs
test/process_managers/process_manager_routing_test.exs
test/process_managers/support/error/default_error_handling_process_manager.ex
test/process_managers/support/error/error_aggregate.ex
test/process_managers/support/error/error_handling_process_manager.ex
test/process_managers/support/error/error_router.ex
test/subscriptions/subscriptions_test.exs
test/test_helper.exs

Allow command dispatch with `consistency: :strong` to be used when Commanded is distributed amongst a cluster of nodes

Support distributed dispatch consistency 

---

README.md
guides/Commands.md
lib/commanded/commands/composite_router.ex
lib/commanded/commands/router.ex
test/commands/composite_router_test.exs
test/commands/routing_commands_test.exs

You can use the `Commanded.Commands.CompositeRouter` macro to define a router comprised of other router modules.
This approach is useful if you prefer to construct a router per context and then combine them together to form a top level application router.
By using `Commanded.Commands.CompositeRouter` in your own module you can include other routers via the `router` macro:
```elixir
defmodule ApplicationRouter do
use Commanded.Commands.CompositeRouter
router BankAccountRouter
router MoneyTransferRouter
end
```

Support composite command routers

---

CHANGELOG.md
README.md
config/test.exs
guides/Aggregates.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/default_lifespan.ex
lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/router.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/event_store/snapshot_data.ex
lib/commanded/serialization/json_serializer.ex
test/aggregates/snapshotting_test.exs
test/aggregates/support/snapshot_aggregate.ex

Allow per aggregate snapshotting to be configured within your app config (e.g. `config/config.exs`). You can define how frequently snapshots should be taken (after every x events) and an optional snapshot version.
```elixir
config :commanded, ExampleAggregate
snapshot_every: 100,
snapshot_version: 1
```
Incrementing the snapshot version will ignore any existing snapshot taken at an earlier version during aggregate state rebuild. This allows you to change the aggregate structure without requiring a snapshot data migration.
Fixes #27.

Aggregate state snapshots

---

CHANGELOG.md
guides/Process Managers.md
lib/commanded/process_managers/failure_context.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
test/process_managers/process_manager_error_handling_state_test.exs
test/process_managers/support/error/context_error_handling_process_manager.ex
test/process_managers/support/error/error_handling_process_manager.ex

This adds a new callback (error/3) for process managers and adds a compile-time warning for those who defines as error/4 to know they have to change.
This is to solve the problem pointed by #123 
Some things that are missing (maybe can be done after this is merged, I'll take a look later, have to go now):
- Add documentation to that
- Reference to a link telling how to change the behaviour in the warning
- Backwards compatibility test? I'm not sure about this and how deep we should test this.
How do we organize these breaking changes to add to a changelog later?
Anyway, what do you think? Is it looking good?
Cheers

Feature: Process manager state on error

---

lib/commanded/process_managers/process_manager.ex

This fixes #130 
Sorry about that. I was messing with elixir internals (`:elixir_errors.warn/1`) for compile time warnings and that was removed in Elixir 1.6.0.
I'm now using the public api `IO.warn/1`.

fix: use IO.warn for compile time warning

---

CHANGELOG.md
config/test.exs
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/aggregate_inspect.ex
lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
lib/commanded/event_store/event_store.ex
test/aggregates/execute_command_test.exs

Retry executing a command if appending events to the aggregate's stream fails with an `{:error, :wrong_expected_version}` concurrency error. The missing event(s) are fetched from the event store to update the aggregate state and attempt the command again.
Aggregate instances are singletons when run on a single node, or cluster if using the distributed registry, so should not fail with this error. However, the change allows Commanded to work when run on multiple nodes that are not connected to form a cluster.

Retry command execution on concurrency error

---

CHANGELOG.md
lib/commanded/commands/dispatcher.ex
lib/commanded/pubsub.ex
lib/commanded/pubsub/local_pubsub.ex
lib/commanded/pubsub/phoenix_pubsub.ex
lib/commanded/subscriptions.ex
lib/commanded/subscriptions/subscriptions.ex
lib/commanded/supervisor.ex
mix.exs
mix.lock
test/commands/support/open_account_bonus_handler.ex
test/pubsub/local_pubsub_test.exs
test/pubsub/phoenix_pubsub_test.exs
test/subscriptions/subscriptions_test.exs

Allow strongly consistent command dispatch to work when Commanded is run on multiple nodes, but not formed as a cluster.
Phoenix's pub/sub library is optionally used since it supports broadcasting messages and tracking presence using PG2 or Redis. The Redis adapter can be used when running multiple nodes that are not connected together. 
The new `Commanded.PubSub` behaviour defines basic pub/sub and process tracking functions. The default implementation uses Elixir's local-only `Registry` module. 
```elixir
config :commanded, pubsub: :local
```
To use Phoenix pub/sub you must add it to your project's depedencies in `mix.exs`:
```elixir
defp deps do
[
{:phoenix_pubsub, "~> 1.0"}
]
end
```
Then configure the Phoenix pub/sub adapter you'd like to use:
```elixir
config :commanded, pubsub: [ …
```

Support distributed dispatch consistency

---

CHANGELOG.md
guides/Events.md
lib/commanded/event/handler.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/event_store/event_store.ex
lib/commanded/process_managers/process_router.ex
mix.exs
mix.lock
test/event/event_handler_macro_test.exs
test/event/handle_event_test.exs
test/event/handler_init_test.exs
test/event/support/appending_event_handler.ex
test/event/support/init/init_handler.ex
test/event_store_adapter/subscription_test.exs
test/example_domain/bank_account/account_balance_handler.ex
test/support/mocks.ex

Expect event store adapters to send a `{subscribed, subscription}` message once successfully subscribed.
This is used to defer initialisation for event handlers, such as calling the `init/0` callback, and process routers. One benefit of deferring `init/0` is that it will only run once, irrespective of how many nodes are running your app and the event handler.

Defer event handler and process router init until after subscribed 

---

CHANGELOG.md
guides/Commands.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/aggregate_lifespan.ex
lib/commanded/aggregates/default_lifespan.ex
lib/commanded/commands/router.ex
test/aggregates/aggregate_lifespan_test.exs
test/aggregates/support/bank_account_lifespan.ex
test/aggregates/support/bank_router.ex
test/commands/routing_commands_test.exs
test/example_domain/bank_account/open_account_handler.ex

An aggregate process lifespan should be controlled by the domain events it creates, not the commands, since a command may be rejected or ignored.
The events created by an aggregate are returned when executing a command so it should be straightforward to call an after_event/1 callback and pass it the last domain event.
- Non-negative integer - specify an inactivity timeout, in millisconds.
- `:infinity` - prevent the aggregate instance from shutting down.
- `:hibernate` - send the process into hibernation.
- `:stop` - immediately shutdown the aggregate process.
Closes #126.

Replace aggregate lifespan `after_command/1` callback with `after_event/1`

---

CHANGELOG.md
guides/Process Managers.md
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
test/process_managers/multi_routing_test.exs
test/process_managers/process_manager_error_handling_state_test.exs
test/process_managers/process_manager_instance_test.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/support/multi/todo.ex
test/process_managers/support/multi/todo_list.ex
test/process_managers/support/multi/todo_process_manager.ex
test/process_managers/support/multi/todo_router.ex

Allow a process manager's `interested?/2` callback to return a list of process identities to handle an event.

Support process manager routing to multiple instances

---

lib/commanded/assertions/event_assertions.ex

Like other helpers, can be brought in with `import Commanded.Assertions.EventAssertions`.
This assertion ensures that:
1. Both events, each matching their respective predicates, are received
2. Both events share the same correlation id
Usage sample follows.
Note that in this example I am using the same identifier to identify the two events out of convenience. 
```elixir
identifier = UUID.uuid4()
assert_correlated(
EventTypeA, &(&1.identifier_a == identifier),
EventTypeB, &(&1.identifier_b == identifier)
)
```

add assert_correlated test helper

---

README.md
guides/testing.md

I never remember to go to the wiki, and I think testing should be a first-class citizen.
This is my first pass on making testing code that uses commanded more approachable. All feedback welcome. :)
(it looks like this: https://github.com/Trevoke/commanded/blob/add-testing-guide/guides/testing.md )

add guide on testing

---

mix.lock
test/event_store_adapter/snapshot_test.exs

The ES adapter tests could fail when the snapshots coincidentially were
created in different minutes, since the seconds were just reset to 0.
This commit updates the logic to consider the difference between
timestamps and asserts a difference no larger than 60 seconds instead.

EventStore adapter tests: Remove flakiness

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/event/handler.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/event_store/event_store.ex
test/aggregates/aggregate_concurrency_test.exs
test/aggregates/aggregate_lifespan_test.exs
test/aggregates/aggregate_subscription_test.exs
test/aggregates/execute_command_test.exs
test/event_store_adapter/subscription_test.exs
test/helpers/storage_case.ex
test/process_managers/support/multi/todo_process_manager.ex
test/support/mock_event_store_case.ex

Each aggregate instance will subscribe to its own events to catch any events appended to an aggregate's stream that were _not_ persisted via the aggregate instance process.
This might happen when events are directly appended to the stream using the configured event store, or when Commanded is run on multiple nodes but they're not connected together to form a cluster.
This pull request will require the two event store adapters be updated as the `Commanded.EventStore` behaviour has been extended to support single stream transient subscriptions.

Aggregate subscribes to its own events

---

lib/commanded/commands/router.ex
lib/commanded/event/handler.ex
test/event/handler_config_test.exs

Why:
* In some situations, particularly when testing, we'll want to have
strong consistency, but that might not be true for the same operation
in a different environment. So, it would be very helpful to be able to
switch between types of consistency per environment.
This change addresses the need by:
* Changing the default from being straight up `:eventual` but instead to
search on the env first and only if nothing is found, then it will
choose `:eventual`
PS: You'll notice that there are no test for the router change. That is because it is set in a module attribute, which being a compile time evaluated property means I cannot affect from the spec. The only way I could think of testing it, would be to create a new environment just for that purpose, which might be an overkill. What do you …

Allows for a default consistency to be set via the env

---

lib/commanded/assertions/event_assertions.ex

changed to use Commanded.EventStore.TypeProvider instead of Atom to get event type

support custom type provider for EventAssertions .

---

test/process_managers/multi_routing_test.exs

assert_receive_event is missing an assert, so the check for list_uuid never fails.
When learning Commanded, I used this example as a template, then later realised none of my tests were failing and I needed to assert inside function.

Add Assertion to ListAllDone event

---

guides/Choosing an Event Store.md

I'm new to CQRS and Commanded. Today I was experimenting with Commanded and came across something that threw me off for a bit. The way I read the docs, the difference between an store and its adapter was not clear, at least for the Postgres adapter, which is the one I used.
I'll elaborate. When reading the section "PostgreSQL-based Elixir EventStore", I clicked on the link "EventStore", opening it on a tab and continued reading. When I saw the phrase advising to follow the "Getting started" guide, I assumed it was the one from the store, not the adapter, not realising that the links led to different repositories. Because of this, I installed the store instead of the adapter, and things didn't work until I finally realised my mistake.
I feel that my proposed changes may help highlighting …

Clear potential adapter/store confusion

---

CHANGELOG.md
guides/Commands.md
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
lib/commanded/event/handler.ex
lib/commanded/middleware/consistency_guarantee.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/subscriptions.ex
test/commands/dispatch_consistency_test.exs
test/commands/support/consistency/optional_strongly_consistent_handler.ex
test/event/event_handler_macro_test.exs
test/process_managers/process_manager_instance_test.exs
test/subscriptions/subscriptions_test.exs

Provide an explicit list of event handler and process manager modules, or their configured names, containing only those handlers you'd like to wait for during command dispatch. No other handlers will be awaited on, regardless of their own configured consistency setting.
```elixir
:ok = BankRouter.dispatch(command, consistency: [ExampleHandler, AnotherHandler])
:ok = BankRouter.dispatch(command, consistency: ["ExampleHandler", "AnotherHandler"])
```
Note you cannot opt-in to strong consistency for a handler that has been configured as eventually consistent.

Command dispatch consistency using explicit handler names 

---

lib/commanded/commands/router.ex

We want to enforce consistent return values in our entire app.
`:include_execution_result` looks exactly like what we want, and
currently fixes two problems for us, so we want to enforce it globally.
I did a similar change to what my colleague zamith already did
previously for another option. however, unlike his case, I didn't find
a good way to test this. Would love to get any input on that front

Ability to globally override include_execution_result and include_aggregate_version

---

lib/commanded/event_store/adapters/in_memory.ex
test/event_store_adapter/in_memory_test.exs

I'm struggling to get the InMemory store to work with my test suite
Following this [wiki page](https://github.com/commanded/commanded/wiki/In-memory-event-store), my conclusion is that the samples shown there are a rather complex way of rebooting the in-memory event store, which requires rebooting the app itself
(I presume this is because the event store is a dependency of the app, or something like that)
The thing is, needing `test --no-start`, and killing my app between tests is a complex thing that leaks that behaviour to the rest of the test suite. I now have to manually start my app in other test files as well, due to the.
Studying the InMemory store for a bit, it seems to be exactly what the name suggests: it keeps stuff in memory. Which is great
If true, that means it should be …

Proposal: InMemory.reset!() for testing purposes

---

lib/commanded/process_managers/process_router.ex
lib/commanded/pubsub/local_pubsub.ex
lib/commanded/pubsub/phoenix_pubsub.ex
mix.exs
test/pubsub/local_pubsub_test.exs
test/pubsub/phoenix_pubsub_test.exs
test/pubsub/support/pubsub_test_case.ex
test/support/shared_test_case.ex

`Phoenix.Tracker` returns `{:error, {:already_tracked, _pid, _topic, _key}}` if the process is already tracked for a given topic/key pair. This is now handled as ok, rather than erroring.

Fix error when subscription process already tracked

---

lib/commanded/pubsub/local_pubsub.ex

Simple change, since the `Registry.match` does not do anything in its match term, we might as well `Registry.lookup` :-)

Local PubSub: Replace noop Registry.match with Registry.lookup

---

guides/Testing.md

@slashdotdash feel free to add the essence of this to the wiki if you prefer that. 
The solution dawned on me when I was looking through Conduit and how it's storage.ex file was setup.

Added Additions to the wiki section to test setup

---

guides/Events.md
guides/Process Managers.md
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
lib/commanded/process_managers/supervisor.ex
test/aggregates/support/example_aggregate.ex
test/aggregates/support/multi_bank_account.ex
test/aggregates/support/snapshot_aggregate.ex
test/event/event_handler_error_handling_test.exs
test/event/support/error/error_aggregate.ex
test/event/support/error/error_event_handler.ex
test/event/support/error/error_router.ex
test/example_domain/bank_account/bank_account.ex
test/example_domain/money_transfer/money_transfer.ex
test/process_managers/process_manager_error_handling_test.exs
test/process_managers/process_manager_instance_exception_test.exs
test/process_managers/process_manager_instance_test.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/support/error/context_error_handling_process_manager.ex
test/process_managers/support/error/error_aggregate.ex
test/process_managers/support/error/error_handling_process_manager.ex
test/process_managers/support/error/error_router.ex
test/process_managers/support/example_aggregate.ex
test/process_managers/support/example_command_handler.ex
test/process_managers/support/example_process_manager.ex
test/process_managers/support/example_router.ex
test/process_managers/support/multi/todo.ex
test/process_managers/support/resume/resume_aggregate.ex

Allow exceptions and errors during event handling to be handled by `error/3` callback functions defined in event handlers and process managers. 
This allows extra resiliency for event handling since exceptions will cause process crashes. These processes are usually supervised and get restarted by the supervisor, they will then retry the same event and likely crash again. This can cause the supervisor itself to crash and propagate further up the supervision tree, eventually causing the application to stop.
The pull request allows the user to decide how to handle problematic events by for example retyring a limited number of times or skipping the event.

Process manager and event handler error & exception handling

---

guides/Process Managers.md
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_router.ex
test/process_managers/process_manager_timeout_test.exs
test/process_managers/support/example_aggregate.ex
test/process_managers/support/example_command_handler.ex
test/process_managers/support/example_process_manager.ex
test/process_managers/support/example_router.ex
test/process_managers/support/resume/resume_process_manager.ex

You can configure a timeout for event handling to ensure that events are processed in a timely manner without getting stuck.
An `event_timeout` option, defined in milliseconds, may be provided when using the `Commanded.ProcessManagers.ProcessManager` macro at compile time:
```elixir
defmodule TransferMoneyProcessManager do
use Commanded.ProcessManagers.ProcessManager,
name: "TransferMoneyProcessManager",
router: BankRouter,
event_timeout: :timer.minutes(10)
end
```
Or may be configured when starting a process manager:
```elixir
{:ok, _pid} = TransferMoneyProcessManager.start_link(event_timeout: :timer.hours(1))
```
After the timeout has elapsed, indicating the process manager has not processed an event within the configured period, the process manager is stopped. The process manager will …

Process manager event handling timeout

---

lib/commanded/aggregates/aggregate.ex
test/aggregates/snapshotting_test.exs

Aggregate is not properly populated from snapshots
`snapshot_valid?` compares `aggregate.snapshot_module_version` with `snapshot.metadata["snapshot_version"]`, but when snapshot is recorded `aggregate.aggregate_version` is saved to new snapshot metadata instead of `aggregate.snapshot_module_version`. If I understand everything correctly `:aggregate_version` changes for every event while `:snapshot_module_version` should be changed by programmer inside config.exs file only when needed.
* Create simple agent `Agent.start_link(fn -> 0 end, name: :foo)`
* Add `Agent.update(:foo, & (&1 + 1))` to every `apply/2` inside aggregate
* Dispatch a command
* `Agent.get(:foo, & &1)` will always return number equal to all events count
* Changed value used to create new snapshot metadata to …

Fix snapshot recording

---

CHANGELOG.md
lib/commanded/aggregates/aggregate.ex
test/aggregates/aggregate_lifespan_test.exs

To ensure the `lifespan_timeout` is always a valid timeout value that can be used for `GenServer` handle callbacks.
Fixes #199.

Set default aggregate lifespan timeout to `:infinity`

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/snapshotting.ex

Will allow process manager state to be snapshotted using same module once event sourced.

Extract aggregate snapshotting to `Commanded.Snapshotting` module

---

lib/commanded/event_store/adapters/in_memory.ex
test/event_store_adapter/append_events_test.exs

The eventstore backend allows to skip the expected version check: (https://github.com/commanded/eventstore/blob/2d031e73a668fb518fc96f0670ccc6ed1deb5bc8/lib/event_store.ex#L44)
This PR will extend this feature to the InMemory adapter.
PR for [eventstore-adapter](https://github.com/commanded/commanded-eventstore-adapter) will follow

Add new values for expected_version

---

lib/commanded/commands/router.ex

Code generated by `use Commanded.Commands.Router` was causing following dialyzer warning:
`lib/my_app/router.ex:1: Expression produces a value of type 'ok' | {'error',_}, but this value is unmatched`

Fixed dialyzer warning generated by "use Commanded.Commands.Router"

---

lib/commanded/commands/router.ex

At the moment dispatch macro generates spec and doc atrributes many times what makes documentation for them confusing. For example output for `iex(1)> h MyApp.Router.dispatch/1` looks like this:
Specs are accumulated and doc from register macro is completely ignored.
What's more, this also causes the following dialyzer warning:
```
lib/my_app/router.ex:4:overlapping_contract
Overloaded contract for MyApp.Router.dispatch/1 has
overlapping domains; such contracts are currently unsupported and
are simply ignored.
```
To fix this I have unified specs and moved them to place where they will be created only once: `__before_compile__` macro

Generate specs and docs for Router dispatch functions only once.

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/aggregate_lifespan.ex
lib/commanded/aggregates/default_lifespan.ex
test/aggregates/aggregate_lifespan_test.exs
test/aggregates/support/bank_account_lifespan.ex
test/example_domain/bank_account/bank_account.ex

Previously, aggregates would not shut down if one or more events were
not returned after command execution. This change defines callbacks to
handle cases where an error or a [] is returned.

Expands AggregateLifespan to include after_command/1 and after_error/1 

---

lib/commanded/assertions/event_assertions.ex
test/event/handle_event_test.exs

Adding second optional parameter to the predicate_fn which now receive the recorded_event as second param, containing all the informations about the event.
I needed to be sure that an event was produce before another one, and I needed to check some metadata too.
```elixir
wait_for_event(
MoneyDeposited,
fn event, recorded_event ->
event.amount == 50 and recorded_event.event_number == 2
end
)
```

Adding recorded_event to predicate_fn in wait_for_event

---

README.md

Add note to README warning that the linked guides follow the `master` branch which may differ from the latest published Hex package.

Include link to latest published Hex package and documentation in README

---

lib/commanded/commands/dispatcher.ex

`Task.yield/1` and `Task.shutdown/1` do not return: `{:error, error}`, only `{:ok, term} | {:exit, term} | nil`

Remove pattern that can not occur

---

lib/commanded/event/handler.ex

name/1 function is used only in handler.ex

Change function to private

---

lib/commanded/snapshotting.ex

With the error being returned without any changes, you do not need the else, only if you want to be explicit

Remove unnecessary else

---

lib/commanded/subscriptions.ex

fixes "warning: deprecated time unit: :seconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer"

Fixed warning about deprecated time unit in elixir 1.8

---

lib/commanded/process_managers/process_manager_instance.ex

Handle the {:ok, _} tuple dispatch result.

---

lib/commanded/pubsub.ex
lib/commanded/pubsub/phoenix_pubsub.ex

There are places where `subscribe/1` `@ spec` is expecting string and not just atom

Fix subscribe/1 '@spec'

---

CHANGELOG.md
guides/Process Managers.md
lib/commanded/commands/router.ex
lib/commanded/event/handler.ex
lib/commanded/process_managers/failure_context.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
test/example_domain/money_transfer/transfer_money_process_manager.ex
test/helpers/event_factory.ex
test/process_managers/process_manager_instance_test.exs
test/process_managers/process_manager_integration_test.exs
test/process_managers/process_manager_routing_test.exs
test/process_managers/support/routing/routing_process_manager.ex
test/support/mocks.ex

Add `:start!` and `:continue!` for strict process routing replies to process manager `interested?/1` callback.
Strict routing enforces the following validation checks:
- `{:start!, process_uuid}` - validate process does not already exist.
- `{:continue!, process_uuid}` - validate process already exists.
If the check fails an error will be passed to the `error/3` callback function:
- `{:error, {:start!, :process_already_started}}`
- `{:error, {:continue!, :process_not_started}}`
The `error/3` function can choose to `:stop` the process or `:skip` the  problematic event.
Fixes #212.

Strict process manager routing

---

CHANGELOG.md
lib/commanded/assertions/event_assertions.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/event_store/event_store.ex
test/event_store/support/subscription_test_case.ex

Unsubscribing an event store subscription should not delete the subscription. This pull request adds `Commanded.EventStore.delete_subscription/2` to allow an existing subscription to be completely removed.
Create a subscription to all events: 
```elixir
{:ok, subscription} = Commanded.EventStore.subscribe_to(:all, "Example", self())
```
Unsubscribe the subscription to stop receiving events, but still remember the subscription's last acknowledged event pointer:
```elixir
:ok = Commanded.EventStore.unsubscribe(subscription)
```
Finally, delete the subscription:
```elixir
:ok = Commanded.EventStore.delete_subscription(:all, "Example")
```

Add `delete_subscription/2` to `Commanded.EventStore` behaviour

---

lib/commanded/event_store/event_data.ex

`data` should be a struct, not a binary.
`metadata` should be a map, not a binary.

Update typespec for EventData.

---

mix.exs

it's required for dependent projects to import `locals_without_parens`

add .formatter.exs to hex package

---

lib/commanded/commands/router.ex

This fixes dialyzer warnings when pattern matching on the results of `Router.dispatch(cmd, include_execution_results: true)`

Add include_execution_result and aggregate_version to type spec.

---

lib/commanded/commands/router.ex

...again.
I just realized that ExecutionResult module was misqualified. 
Sorry for the thrash.

Fix typespec for `Router.dispatch`.

---

lib/commanded/aggregates/aggregate.ex
test/aggregates/execute_command_test.exs
test/aggregates/support/return_value_aggregate.ex

Add support to allow the following values to be returned by a command handler function, such as aggregate `execute/2` functions.
| Aggregate return value | Events produced |
|-------------|------------------|
| `:ok`, `nil` , `[]` | none |
| `event` , `{:ok, event}` | one event |
| `[event1, event2, ..]` , `{:ok, [event1, event2, ..]}` | list of events |
| `{:error, reason`} | an error occurred |
Closes #52.

Support `:ok` tagged tuple events from aggregate

---

lib/commanded/event/handler.ex
lib/commanded/process_managers/process_router.ex
lib/commanded/subscriptions.ex
lib/commanded/subscriptions/registry.ex
lib/commanded/supervisor.ex
test/subscriptions/subscriptions_test.exs

Use an ETS table to track `:strong` event store subscriptions. Previously subscriptions were tracked using the configured pub/sub provider, `Registry` for local deployment and Phoenix pubsub for distributed. 
The Phoenix pubsub provider when used with Redis occasionally failed to correctly track processes and took a few seconds during application start up. This pull request uses a local ETS table to track subscriptions for more reliability.

Register event handler and process manager subscriptions on process start

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/supervisor.ex
lib/commanded/registration/local_registry.ex
lib/commanded/registration/registration.ex
test/event/upcaster_test.exs
test/registration/support/registered_server.ex
test/registration/support/registered_supervisor.ex

In order to support DynamicSupervisor, Commanded.Registration.start_child/3
needed to receive a child_spec instead of args like a :simple_one_for_one
supervisor would expect. Supporting DynamicSupervisor will allow us to
support distributed supervisors like Horde.Supervisor.

Modify Registration.start_child/3 to pass a child_spec

---

lib/commanded/aggregates/supervisor.ex
lib/commanded/registration/local_registry.ex
lib/commanded/registration/registration.ex
test/registration/support/registration_test_case.ex

This will allow us to swap out Supervisor implementations, supporting
Horde.Supervisor for example. Supersedes the approach in #274

Add supervisor_child_spec/2 to Commanded.Registration

---

CHANGELOG.md
lib/commanded/event_store/snapshot_data.ex
lib/commanded/serialization/json_serializer.ex
mix.exs
test/middleware/halting_middleware_test.exs
test/middleware/middleware_test.exs
test/middleware/support/commands.ex

Derive `Jason.Encoder` protocol only if the `Jason` module is available.
Fixes #275.

Ensure Commanded can be compiled when optional Jason dependency is not present

---

.travis.yml
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
lib/commanded/process_managers/supervisor.ex
test/process_managers/process_manager_idle_timeout_test.exs
test/process_managers/process_manager_instance_test.exs
test/process_managers/support/example_router.ex
test/process_managers/support/timeout_process_manager.ex

Every started instance of a process manager runs indefinitely. To reduce memory usage this pull request adds an idle timeout configuration (in milliseconds) after which an instance process will be shutdown.
The process will be restarted on demand, whenever an event is routed to it, and its state will be rehydrated from the instance snapshot.
Define the `idle_timeout` option in the process manager module:
```elixir
defmodule ExampleProcessManager do
use Commanded.ProcessManagers.ProcessManager,
name: "ExampleProcessManager",
router: ExampleRouter,
idle_timeout: :timer.minutes(10)
end
```
Or provide the timeout on start:
```elixir
ExampleProcessManager.start_link(idle_timeout: 10_000)
```
By default the idle timeout will be configured as `:infinity` so every process manager instance will …

Process manager idle process timeout

---

lib/commanded/pubsub/phoenix_pubsub.ex

This is more of a PR for discussion on the best approach.
Currently the supervisor is calling `PubSub.child_spec/0` which in turn sets passes the options defined in `config/*.exs` down to `Phoenix.PubSub`.
With this setup, it is non-trivial to set values in runtime (like some environment variables which are not always available in compile time) for PubSub. It would be possible to overwrite the supervisor but we would need to explicitly start the tracker, among others.
The approach we went with was to change the `Commanded.PubSub.PhoenixPubSub` module to account for variables in the format of `{:system, varname}`. This is very hackish, however. Ideally this could be something set in the supervisor and propagated down or even to use an existing PubSub instance started in the supervisor, …

Support {:system, varname} format in Phoenix PubSub

---

CHANGELOG.md
README.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
test/aggregates/aggregate_concurrency_test.exs
test/event/handler_init_test.exs
test/process_managers/process_manager_routing_test.exs
test/process_managers/process_manager_subscription_test.exs

Due to invalid name being passed to event store subscription.
Use `handle_continue` callback to subscribe to event store for event handlers to be consistent with process managers.

Fix process manager exception on start

---

test/support/aggregate_case.ex

Issue #314 
This `aggregate_case` could be use to create aggregates unit tests in order to check:
* raised events by aggregates
* aggregates states
* errors handling commands

Add `AggregateCase` ExUnit case template to support aggregate unit testing 

---

lib/commanded/commands/dispatcher.ex

When running Dialyxir on a project that dispatches commands with either the `include_execution_result: true` or `include_aggregate_version: true` options set, an error would be encountered due to the incomplete typespec on the `Commanded.Commands.Dispatcher.dispatch/1` function. This change simply updates the documentation and the typespec to match the actual implementation. It is a nonfunctional change.

Fixes the typespec for command dispatch

---

guides/Deployment.md

Hi, first of all thank you for maintaining commanded and its ecosystem! 🎉 
This PR is just a fix in the `commanded_swarm_registry` version and a note about running EventStore in a clustered environment.

Improve Deployment Guite

---

CHANGELOG.md
lib/application.ex
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/composite_router.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/execution_result.ex
lib/commanded/commands/router.ex
lib/commanded/process_managers/process_manager_instance.ex
test/aggregates/aggregate_concurrency_test.exs
test/aggregates/execute_command_test.exs
test/commands/dispatch_consistency_test.exs
test/commands/dispatch_return_test.exs
test/commands/routing_commands_test.exs
test/commands/support/returning/default_dispatch_return_app.ex

By default a successful command dispatch will return `:ok`. This pull request allows changing the default behaviour by specifying a `returning` option during command dispatch.
The supported options are:
- `:aggregate_state` - to return the update aggregate state.
- `:aggregate_version` - to return only the aggregate version.
- `:execution_result` - to return a `Commanded.Commands.ExecutionResult`
struct containing the aggregate's identity, state, version, and any events
produced from the command along with their associated metadata.
- `false` - don't return anything except an `:ok` (default).
Note this only affects successful command dispatch. If the command dispatch produces an error then it will always be returned, irrespective of the `returning` option.
```elixir
{:ok, %BankAccount{}} …
```

Command dispatch return

---

CHANGELOG.md
config/test.exs
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/registration/local_registry.ex
test/aggregates/aggregate_test.exs
test/aggregates/execute_command_test.exs
test/event/handle_event_test.exs
test/process_managers/process_manager_instance_test.exs
test/support/mocks.ex

Implement catch-all `handle_info/2` callback function for event handler and process manager instance `GenServer` processes.
Fixes #332.

Log and ignore unexpected messages received by event handlers and process manager instances

---

CHANGELOG.md
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
test/process_managers/dynamic_process_manager_application_test.exs
test/process_managers/process_manager_idle_timeout_test.exs
test/process_managers/process_manager_routing_test.exs
test/process_managers/process_manager_timeout_test.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/resume_process_manager_test.exs

Fix bug whereby an empty list returned by a process manager's `interested?/1` function causes the process router to hang indefinitely.
Fixes #185.

Process manager stops if `interested?/1` returns an empty list

---

CHANGELOG.md
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
test/process_managers/process_manager_instance_test.exs
test/process_managers/support/identity/identity_process_manager.ex

Used to determine the identity of the current process manager instance.
```elixir
defmodule ExampleProcessManager do
use Commanded.ProcessManagers.ProcessManager,
application: MyApp.Application,
name: __MODULE__
def interested?(%ProcessStarted{uuids: uuids}), do: {:start, uuids}
def handle(%ExampleProcessManager{}, %ProcessStarted{} = event) do
uuid = Commanded.ProcessManagers.ProcessManager.identity()
end
end
```
Fixes #320.

Process manager `indentity/0` function

---

.travis.yml
config/config.exs
lib/commanded/event_store/type_provider.ex
test/commands/support/aggregate_root.ex
test/commands/support/command_timeout_handler.ex
test/commands/support/identity/identity_function_router.ex
test/commands/support/timeout_command.ex
test/commands/support/timeout_router.ex
test/commands/support/unregistered_command.ex
test/event/support/ignored_event.ex
test/event/support/uninteresting_event.ex
test/process_managers/support/example_router.ex
test/process_managers/support/resume/resume_command_handler.ex

This PR makes sure that all code pushed to `commanded` is formatted. I'm initially pushing it up unformatted to show that it works, then I will format and push a second commit.

Run the formatter in CI

---

lib/commanded/event/handler.ex
test/event/default_event_handler_error_handling_test.exs
test/event/handle_event_test.exs
test/event/support/error_event.ex
test/example_domain/bank_account/account_balance_handler.ex
test/example_domain/bank_account/bank_account.ex

#303 
This PR logs the stacktrace when a user-written EventHandler raises an error. 
Note that I hacked in a test scenario, there might be a better way of doing that. I'm open to suggestions.

Add stacktraces to EventHandler error logging

---

CHANGELOG.md
lib/commanded/assertions/event_assertions.ex
test/event_assertions_test.exs

Subscription is created from `:current` to ensure only events produced by the given function are considered as failing. Any existing events are ignored. The `refute_receive_event/4` macro is also changed to a function.
Refute that `ExampleEvent` is produced by given anonymous function:
```elixir
refute_receive_event(ExampleApp, ExampleEvent, fn ->
:ok = MyApp.dispatch(command)
end)
```
Refute that `ExampleEvent` produced by `some_func/0` function is published to a given stream:
```elixir
refute_receive_event(ExampleApp, ExampleEvent, &some_func/0,
predicate: fn event -> event.value == 1 end,
stream: "foo-1234"
)
```

`refute_receive_event/4` only tests newly created events

---

CHANGELOG.md
lib/commanded/event/handler.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/event_store/recorded_event.ex
lib/commanded/event_store/subscription.ex
lib/commanded/process_managers/process_router.ex
mix.exs
mix.lock
test/event/event_handler_subscription_test.exs
test/process_managers/process_manager_subscription_test.exs

Restarting an event handler or process manager, such as after a crash when supervised, may encounter an error attempting to subscribe to the event store. Instead of crashing the process again, the subscription will attempt be retried with an exponentially increasing delay, including random jitter. The maximum delay between attempts is one minute. This will allow an event handler or process manager to recover more gracefully on error.

Retry event handler and process manager suscriptions on error

---

CHANGELOG.md
config/test.exs
lib/commanded/commands/dispatcher.ex
test/middleware/application_middleware_test.exs
test/middleware/support/tenant/tenant.ex
test/middleware/support/tenant/tenant_app.ex
test/middleware/support/tenant/tenant_middleware.ex
test/middleware/support/tenant/tenant_router.ex

Allow setting the Commanded Application name in router middleware to support dynamic applications, such as using tenant-specific a app and event store.
```elixir
defmodule TenantMiddleware do
@behaviour Commanded.Middleware
alias Commanded.Middleware.Pipeline
def before_dispatch(%Pipeline{} = pipeline) do
%Pipeline{command: command} = pipeline
tenant_id = Map.fetch!(command, :tenant_id)
application = Module.concat([TenantApp, "tenant#{tenant_id}"])
%Pipeline{pipeline | application: application}
end
def after_dispatch(pipeline), do: pipeline
def after_failure(pipeline), do: pipeline
end
```

Allow Commanded Application name to be set dynamically in middleware

---

guides/Commands.md
lib/commanded/commands/router.ex
test/commands/routing_commands_test.exs
test/commands/support/aggregate_root.ex
test/commands/support/aggregate_router.ex

There is an existing yet undocumented option to the
`Commanded.Commands.Router`'s `dispatch` macro that allows you to
specify the name of the function that will be called on the aggregate to
which the command is being dispatched (i.e. you can use a method other
than `execute/2` on your aggregate).
Using this option allows one to have more specifically-named functions on
an aggregate (vs. just pattern matching `execute/2` based on the type of
command, etc.) without requiring the use of a command handler module
when one is otherwise unnecessary. This results in fewer lines of code
as well as fewer layers of abstraction while allowing for the option of
self-documenting function names.
Although the necessary behavior was already in place, because it was
neither documented nor directly tested, …

Test and document dispatch's :function option

---

guides/Commands.md

Updates documentation to clarify that the execution context of command
handlers is the same as the aggregate; the command handler is executed
in the same GenServer process and is within the consistency boundary of
the aggregate.

Clarify execution context for command handlers

---

lib/commanded/aggregates/aggregate.ex

I tried benchmarking both solutions and the time it takes is around 60% of the old implementation.
Even bigger difference is in the amount of memory being allocated and not released during the rebuild. With old implementation it gradualy rises into gigabytes. With new implementation it stays around 100-200 megabytes. I am not sure if the Stream is not used correctly, or if there's some bug in the Stream internals or if it's just my special case, but it could be useful if somebody could do some benchmarks with his data to prove my suspicion.
**Before change:**
**After change:**
I tested this on around `100_000` events stored as JSONB in PostgreSQL.
Benchmarking machine:
```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
Number of Available Cores: 4 …
```

Fix high memory consumption during aggregate rebuild

---

lib/commanded/event_store/adapters/in_memory.ex

I'm not sure if this is just a problem in our codebase, or if it should also be handled here in some way, so opening the discussion.
After getting our commanded 1.0 upgrade ready, we're having a few sporading build errors because `InMemory.reset!` sometimes fails with `{:error, :not_found}`.
We believe this is caused when somehow a handler ends up stopping when cleaning up the test, but before the reset call is made. Since this only affects the clean-up part of a test, I feel it should be safe to ignore this particular error

Ignores :not_found when reseting InMemory store

---

CHANGELOG.md
lib/commanded/event/handler.ex
test/event/event_handler_error_handling_test.exs
test/event/support/error/error_aggregate.ex
test/event/support/error/error_event_handler.ex

The valid return values for an event handler's `handle/2` callback function are `:ok` or `{:error, term}`. Returning any other value previously caused the handler to crash with a CaseClauseError. This is now caught and will call the handler's `error/3` callback function allowing the handler to decide what to do.
Closes #371.

Call event handler's `error/3` callback function when `handle/2` function returns an invalid value

---

CHANGELOG.md
lib/commanded/event/upcast.ex
test/event/support/upcast/events.ex
test/event/upcaster_test.exs

We allowing the Upcaster protocol casses to RecordedEvent metadata regarding the event.
This will allow to solve idepotency issues on EventHandlers and ProcessManagers by allowing to do checks based `event_uuid` or `event_number` as well as having access to `created_at` fields and correlation/causation, stream info.
This PR addresses #339 directly but also indirectly solves #327

Allow metadata in upcaster

---

lib/commanded/aggregates/multi.ex

Events returned by `Multi.execute` calls are not persisted if followed by `Multi.execute` calls that return another `multi` instead of events.

Fix multi aggregate

---

CHANGELOG.md
guides/Events.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/event/failure_context.ex
lib/commanded/event/handler.ex
lib/commanded/event/upcast.ex
lib/commanded/event/upcaster.ex
lib/commanded/event_store.ex
lib/commanded/event_store/recorded_event.ex
lib/commanded/process_managers/process_router.ex
test/event/event_handler_error_handling_test.exs
test/event/event_handler_name_test.exs
test/event/event_handler_subscription_test.exs
test/event/handle_event_test.exs
test/event/handler_init_test.exs
test/event/reset_event_handler_test.exs
test/event/support/echo_handler.ex
test/event/support/init/runtime_config_handler.ex
test/event/support/reply_event.ex
test/event/support/upcast/event_handler.ex
test/event/upcaster_test.exs
test/helpers/event_factory.ex

Include the associated Commanded Application and event handler name as additional system provided metadata key/values. This allows event handlers to determine the current application and handler name when started with these options configured at runtime.
```elixir
defmodule ExampleEventHandler do
use Commanded.Event.Handler
@impl Commanded.Event.Handler
def handle(event, metadata) do
application = Keyword.fetch!(metadata, :application)
handler_name = Keyword.fetch!(metadata, :handler_name)
:ok
end
end
```
Usage:
```elixir
{:ok, _pid} = ExampleEventHandler.start_link(application: MyApp, name: "ExampleEventHandler1")
{:ok, _pid} = ExampleEventHandler.start_link(application: MyApp, name: "ExampleEventHandler2")
```
The above demonstrates using the same event handler module but configured at …

Include `application` and `handler_name` as additional event handler metadata

---

CHANGELOG.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_router.ex
lib/commanded/registration.ex
lib/commanded/registration/adapter.ex
lib/commanded/registration/global_registry.ex
lib/commanded/registration/local_registry.ex
test/event/handler_init_test.exs
test/registration/support/registration_test_case.ex

Allow `:timeout`, `:debug`, `:spawn_opt`, and `:hibernate_after` options to be passed through to [`GenServer.start_link/3`](https://hexdocs.pm/elixir/GenServer.html#start_link/3) when starting event handlers and process managers.
```elixir
{:ok, pid} = MyEventHandler.start_link(hibernate_after: :timer.seconds(15))
```
Or supervised:
```elixir
Supervisor.start_link(
[
{ExampleHandler, hibernate_after: :timer.seconds(15)}
],
strategy: :one_for_one
)
```

Allow `GenServer` start options to be provided when starting event handlers and process managers

---

CHANGELOG.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/supervisor.ex
lib/commanded/application/supervisor.ex
lib/commanded/event/handler.ex
lib/commanded/event_store/adapters/in_memory.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_router.ex
lib/commanded/subscriptions.ex
lib/commanded/subscriptions/registry.ex
test/application/application_supervisor_test.exs

The `hibernate_after` option is used by the Commanded application's top-level supervisor when starting its children. This determines whether the internal `GenServer` processes used by Commanded, such as the aggregates dynamic supervisor, hibernate after a period of inactivity. See [`GenServer.start_link/3`](https://hexdocs.pm/elixir/GenServer.html#start_link/3) for details.
The default value is `:infinity` which disables hibernation. You can configure the value when defining or starting your own Commanded application.
Configured at compile-time:
```elixir
defmodule MyApp do
use Commanded.Application, 
otp_app: :my_app, 
hibernate_after: :timer.minutes(1)
end
```
Configured at runtime:
```elixir
{:ok, _pid} = MyApp.start_link(hibernate_after: :timer.minutes(1))
```
Or supervised:
```elixir …
```

Add `hibernate_after` option to application config

---

CHANGELOG.md
lib/commanded/event/failure_context.ex
lib/commanded/event/handler.ex
lib/commanded/process_managers/failure_context.ex
test/event/event_handler_state_test.exs
test/event/handle_event_test.exs
test/event/support/state/stateful_event_handler.ex
test/helpers/process_helper.ex

An event handler can define and update custom state which is held in the `GenServer` process' memory. It is passed to the `handle/2` function as part of the metadata using the `:state` key. The state is transient and will be lost whenever the process restarts. 
Initial state can be set in the `init/1` callback function by adding a `:state` key to the config. It can also be provided when starting the handler process:
```elixir
ExampleHandler.start_link(state: initial_state)
```
Or when supervised:
```elixir
Supervisor.start_link([
{ExampleHandler, state: initial_state}
], strategy: :one_for_one)
```
State can be updated by returning `{:ok, new_state}` from any `handle/2` function. Returning an `:ok` reply will keep the state unchanged.
Handler state is also included in the …

Support custom state for event handlers

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/dispatcher.ex
lib/commanded/commands/router.ex
test/commands/routing_commands_test.exs

Add an optional `before_execute/2` callback to Aggregates, called just before the `execute/2` callback, with the user-defined aggregate state and the current execution context. This is particularly useful to do some setup in the context of the aggregate process (e.g. set the aggregate's own logger's metadata).
See issue https://github.com/commanded/commanded/issues/403

Pass execution context to aggregates before execution

---

lib/commanded/commands/router.ex
test/commands/command_identity_test.exs

closes #394, adding `:command_uuid` to the list of options to `Commanded.Commands.Router.dispatch/2`

Command Identity

---

.formatter.exs
lib/commanded/aggregates/aggregate.ex
mix.exs
mix.lock

Contributes to #387
Adds two telemetry events to the Aggregate GenServer
1. [:commanded, :aggregate, :execute, :start]
2. [:commanded, :aggregate, :execute, :stop]
Each provide the `%ExecutionContext{}` and `%Aggregate{}` as metadata.
This allows metrics and tracing instrumentation elsewhere.
As an example of how this can be useful, I have built a small working
prototype here.
https://github.com/davydog187/foosball

 start/stop Aggregate telemetry events

---

lib/commanded/event/handler.ex

Follows #407 (and currently branched off of)
Contributes to #387 
Adds telemetry to `Event.Handler.handle/2`. For this one, I made a separate event for error, which aligns with https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router.ex#L345
I will backport the error event to the other PR

start/stop/error Event.Handler telemetry events

---

lib/commanded/event/handler.ex

Align telemetry errors with the spec, such that they correctly are discoverable from `TelemetryRegistry.spannable_events/0`

telemetry :error -> :exception

---

lib/commanded/event/handler.ex

While working on the tracing bridge library, found these two incorrectly named events that slipped through review.

Fix event names

---

lib/commanded/aggregates/aggregate.ex
lib/commanded/aggregates/execution_context.ex
lib/commanded/event/handler.ex
lib/commanded/telemetry.ex
test/aggregates/aggregate_telemetry_test.exs

Follow the conventions defined in the [telemetry](https://hexdocs.pm/telemetry/) library's `span/3` function for naming convention (`:start`, `:stop`, `:exception`) and the structure of measurements and metadata.

Define `Commanded.Telemetry` module to emit consistent telemetry events

---

guides/Serialization.md

The example uses `:eventstore` as the app to configure, which is either out-of-date, or misleading.

Fix the commanded serialization guide

---

lib/commanded/process_managers/process_manager.ex

The macro doesn't define a struct for you. This makes it closer to making the example "compile" if it were real code.

Fix the Process Manager example

---

lib/commanded/process_managers/process_manager.ex

- `init/1`
- `handle/2`
- `apply/2`
- `error/3`
- `interested?/1`
This will improve the documentation, see https://hexdocs.pm/elixir/GenServer.html#c:handle_info/2 for an example

Mark ProcessManager callbacks as optional

---

mix.exs
mix.lock

Pulls in my PR to `telemetry_registry`, which fixes the ordering of generated telemetry event documentation 
https://github.com/beam-telemetry/telemetry_registry/pull/9

Fix the telemetry event ordering

---

mix.exs

This PR should hopefully make the documentation sidebar massively easier to read and navigate. This one has been bugging me for a while, luckily https://github.com/elixir-lang/ex_doc has a great solution with `:nest_modules_by_prefix`!

Make the documentation sidebar more readable

---

lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
test/process_managers/process_manager_telemetry_test.exs

Adds telemetry events for Process Managers.
Contributes to https://github.com/commanded/commanded/issues/387

Telemetry [:commanded, :process_manager, :handle]

---

lib/application.ex
lib/commanded/commands/dispatcher.ex
test/application/telemetry_test.exs

Adds telemetry to the dispatcher, which will add start and stop events
to all dispatches.
Contributes to https://github.com/commanded/commanded/issues/387

Telemetry [:commanded, :application, :dispatch]

---

lib/commanded/commands/router.ex
test/commands/routing_commands_test.exs

When a non-map type metadata is entered, Raise an exception.

Make sure the metadata must be map type.

---

lib/commanded/commands/dispatcher.ex

Retry failed command dispatch due to the registered node for an aggregate being down when we try to execute against it.
Given an Aggregate A that was spawned on Node X and a command for A is
received on Node Y. If X is shutdown/killed after Y has
located the process for A on X, then the command will fail.
This PR allows the command to be retried, which will result in a new process
for A being opened on Node Y and the command will succeed from the
caller's perspective.

Retry command execution on node down

---

.github/workflows/test.yml

The EEF has taken ownership over the GHA for setting up Elixir/Erlang. The previous action is now archived. https://github.com/erlef/setup-beam

Migrate to erlef/setup-beam

---

CHANGELOG.md
lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/router.ex
test/commands/dispatch_return_test.exs
test/example_domain/bank_router.ex

Extend command dispatch `returning` option to support `:events` to return the resultant domain events.
```elixir
{:ok, events} = BankApp.dispatch(command, returning: :events)
```

Dispatch returning resultant events

---

mix.exs

The bump to 1.0 only solidifies the public API. It's the same as the 0.4 series, just with a guarantee of a stable API. Since there are libraries that have not updated yet, accepting both for now seems reasonable.

Allow for telemetry 1.0

---

mix.exs

Hex has a nice mix task called `hex.sponsor` which shows all packages with a "Sponsor" link. You only need to add a URL in the `links` map called `Sponsor` and Hex will show it whenever anyone runs `mix hex.sponsor`. Can't hurt to add it.
Info on the mix task: https://hexdocs.pm/hex/Mix.Tasks.Hex.Sponsor.html#content

Add sponsorship information to mixfile

---

lib/commanded/event/handler.ex
test/event/event_handler_state_test.exs
test/event/handler_init_test.exs

Hello!
I've experience the following issues that I don't think its the intended behaviour.
Im using and Event Handler state for saving dynamic information and restoring on the `init/1` callback.
Last week a EH crashed to my surprise the EH process, the new one that the supervisor started, did not run the `init/1`
The reason for this is that `init/1` was called once in the `child_spec` definition and it was not calling the module start link.
So what end up happening is that the init/1 is called only once at the first start of the Event Handler
With this change the only downside that im seeing is that `parse_config!` is called in the `child_spec` and also in the `start_link`
I haven't found a way to get around that, because in the `init/1` callback you can define the application and the …

Event Handler not calling init on restart

---

lib/commanded/process_managers/process_manager.ex
test/process_managers/process_manager_init_test.exs

Ensure the `init/1` callback function is called whenever a process manager restarts.

Call process manager `init/1` function on process restart

---

lib/commanded/event_store.ex
test/event_store/telemetry_test.exs

Adds telemetry events to the `Commanded.EventStore` adapter
I am going to avoid using the TelemetryRegistry for documenmting these events until it has better support for generating span documentation, otherwise, it will overtake this module. If you're ok with that @slashdotdash then I'm happy to convert to `telemetry_event` definitions

EventStore telemetry events

---

lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
test/process_managers/process_manager_after_command_text.exs
test/process_managers/process_router_process_pending_events_test.exs
test/process_managers/support/after_command_process_manager.ex

fixes https://github.com/commanded/commanded/issues/441
This PR allow a process manager instance to be stopped through `after_command/1` callback function.
The`after_command/1` callback function can have two return values, `:stop` that would stop with specific command and `:continue` that would ignore the command.
The callback function would only be called after the command is successfully dispatched. 
After commands are successfully dispatched the Process state snapshot would be deleted as it would be in the `interested?/1` callback implementation.

Allow a process manager to stop after dispatching a command

---

config/bench.exs
config/config.exs
config/dev.exs
config/prod.exs
config/test.exs

Available since Elixir [1.9.0](https://hexdocs.pm/elixir/1.13.1/Config.html#config/2)
Fixes warnings on Elixir 1.13

use Mix.Config -> import Config

---

mix.exs
mix.lock

As we talked at #477, i'm adding the `credo` dependency as optional so you can evaluate what's better for the existing coding style

Add credo dependency as optional

---

.github/workflows/test.yml

This PR intends to fix error `:dialyzer.run error: Old PLT file /home/runner/work/commanded/commanded/priv/plts/commanded.plt` using a more verbose key for cache, i.e.:`Linux-OTP-23.3.4.11-v1.13.2-otp-23-plts` instead of `Linux-24.2-1.13.2-plts` so it should avoid that the cache doesn't cause issues with Dialyzer and Elixir versions changing out from under you.

Fix Dialyzer old PLT file error

---

lib/commanded/process_managers/process_manager.ex

The docs for `1.4.0-rc.0` are missing a backtick:

Fix docs layout issue

---

lib/commanded/commands/router.ex

[Doc] Fix Router moduledoc code formatting

---

lib/commanded/process_managers/process_manager.ex

This PR intends to fix process manager telemetry event measurements documentation, from `%{system_time: integer()}` to `%{duration: non_neg_integer()}`.

Fix process manager telemetry event measurements documentation

---

lib/commanded/aggregates/aggregate_state_builder.ex

100 is fairly small, and 1_000 is used elsewhere (event_store.ex) as a default.

Set read event batch size to a somewhat saner value

---

lib/commanded/aggregates/aggregate.ex

We found that there may be occasional `:noproc` errors raised during the function call in `Commanded.Commands.Dispatcher.execute/3`
The error looks like this:
```elixir
Erlang error:
{:noproc,
{
GenServer,
:call,
[
{:via, Registry, {MyApp.EventApp.LocalRegistry, {MyApp.EventApp, MyApp.Aggregators.MyAggregator, "my-stream-id"}}},
{
:execute_command,
%Commanded.Aggregates.ExecutionContext{
before_execute: nil,
causation_id: "...",
command: %MyApp.Commands.SomeCommand{},
correlation_id: "...",
function: :execute,
handler: MyApp.Aggregators.MyAggregator,
lifespan: MyApp.Lifespans.MyLifeSpan,
metadata: %{},
retry_attempts: 10,
returning: false
}
},
5000
]
}
}
```
> **Note**
> we're using a lifespan so the aggregator can terminate itself after some idle.
Looking at the code, I think it could be …

Retry command execution when the aggregate process is down

---

lib/application.ex
lib/commanded/commands/router.ex

I had to copy over such typespec https://github.com/straw-hat-team/beam-monorepo/blob/a4b2551aa29171e4d73cfbef9319b8013e6318a7/apps/one_piece_commanded/lib/one_piece/commanded/helpers.ex#L8-L15
I tried to clean up a bit to allow packages around Commanded to be more in line with the spec, and also, consequently, the code base is more cohesive, I think, less copy-pasta.

chore: improve typespec for router dispatch resp

---

lib/application.ex

I think dialyzer did not catch this one because it ignores test files and that's the only place this macro is called? This was introduced in #484

Fix typespec typo in Commanded.Application

---

lib/commanded/event/handler.ex
lib/commanded/process_managers/process_manager.ex

Moves opts out of module attributes for process managers and event handlers. The opts can reference modules which will cause [compile-time dependencies](https://hexdocs.pm/elixir/1.14/Kernel.html#@/1-attention-compile-time-dependencies) if they are in module attributes.

Reduce compile-time dependencies

---

lib/application.ex

I noticed that there is an inconsistency (😄) between the [wiki](https://github.com/commanded/commanded/blob/master/guides/Commands.md#command-dispatch-consistency-guarantee) and the commanded documentation.
Feel free to change the wording.

Add docs for event handler modules consistency dispatch option

---

lib/commanded/event/upcaster.ex

Upcaster is mostly referenced for updating historical events, but it also run on new events.
It wont hurt to clarify that in the docs :)

Update upcaster docs

---

README.md
lib/commanded/aggregates/aggregate.ex
lib/commanded/event/handler.ex
lib/commanded/middleware/consistency_guarantee.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
mix.exs

When using commanded with Elixir 1.15, we currently see a lot deprecation warnings for `Logger.warn/1`:
```
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead                                                                                                                                                   
lib/commanded/middleware/consistency_guarantee.ex:47: Commanded.Middleware.ConsistencyGuarantee.after_dispatch/1
```
It should be fine to change `Logger.warn/1` to `Logger.warning/1` because the _new_ function already exists since Elixir 1.11.
FYI: `eventstore` already has already been updated to use `Logger.warning/1`: https://github.com/commanded/eventstore/pull/278
---
@slashdotdash What about this? :arrow_down_small: …

Use `Logger.warning` to fix deprecation warnings

---

lib/commanded/process_managers/process_manager.ex

Looking at the documentation, i expected this to work by putting in the domain event resulting in the command dispatches, but this is taking the command type.

Correct callback parameter type in after_command process_manager.ex

---

lib/commanded/event_store/recorded_event.ex
lib/commanded/process_managers/process_manager.ex
lib/commanded/process_managers/process_manager_instance.ex
lib/commanded/process_managers/process_router.ex
test/event_store/recorded_event_test.exs
test/example_domain/bank_account/bank_account.ex
test/example_domain/money_transfer/transfer_money_process_manager.ex
test/process_managers/process_manager_after_command_test.exs
test/process_managers/process_manager_instance_test.exs
test/process_managers/process_manager_routing_test.exs
test/process_managers/support/after_command_process_manager.ex
test/process_managers/support/example_aggregate.ex
test/process_managers/support/example_command_handler.ex
test/process_managers/support/example_router.ex
test/process_managers/support/routing/routing_process_manager.ex

The PR addresses #440 and allows metadata read access from all callbacks except `error/3` (as the last one already has access to full RecordedEvent struct).
Supports both old and new callback versions (with and without metadata as the last parameter)
Also adds copying metadata from processed events to new commands by default. 
Modification of the metadata inside the process manager `handle/3` and `handle/2` callbacks are subject of the possible next PR.

Process manager metadata read access

---

lib/commanded/event_store/event_data.ex

I believe `causation_id` and `correlation_id` are optional fields (for example `lib/commanded/event/mapper.ex:55` sets to a value that can be nil), updated the typespec accordingly.

Fix EventData typespec

---

lib/commanded/assertions/event_assertions.ex

Some of the code examples for `refute_receive_event` are not rendering correctly:
This PR fixes the indentation, which should fix the problem.

Fix refute_receive_event examples

---

lib/commanded/process_managers/process_manager.ex

Just a small typo in the interested/2 function doc.

Fix interested? function doc

---

lib/commanded/aggregates/execution_context.ex
lib/commanded/commands/dispatcher.ex
test/aggregates/aggregate_concurrency_test.exs
test/aggregates/aggregate_state_test.exs
test/aggregates/aggregate_subscription_test.exs
test/aggregates/aggregate_telemetry_test.exs
test/aggregates/event_persistence_test.exs
test/aggregates/execute_command_test.exs
test/aggregates/snapshotting_test.exs

Assign `aggregate_state`, so that we can write middlewares to do more things about the `aggregate_state` in the `after_dispatch` stage.

feat: put aggregate_state into assigns of the pipeline

---

test/event_store/support/subscription_test_case.ex

[commanded-spear-adapter](https://github.com/fabriziosestito/commanded-spear-adapter) does not support partitioning.
Adding a test tag to partitioning related test to skip the test completely.

Add tag to partition test case

---

.github/workflows/test.yml

Some GitHub actions are throwing warnings:
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Updating actions/checkout and actions/cache

Update Github actions version to the latest

---

guides/Commands.md

Updating the documentation for the `dispatch/2` option `include_aggregate_version` to make it more clear how the returned `aggregate_version` can be used.

Update include_aggregate_version documentation

---

lib/commanded/aggregates/aggregate.ex
test/aggregates/aggregate_lifespan_test.exs

Based on @bougueil's issue and work here:
https://github.com/commanded/commanded/pull/600
He found 3 cases where an agggregate's lifespan would be cancelled unintentionally.
Specifically
1) Calling `Aggregate.aggregate_state/3`
2) Calling `Aggregate.aggregate_version/3`
3) If the aggregate process receives any unhandled message
The work here is to add tests and provide a unified way of sending `:reply` or `:noreply` along with the lifetime info.

Aggregate.handle_* now properly handles lifespans

---

lib/commanded/registration.ex

Commanded modules ProcessRouter, Aggregate, and Event.Handler all `use` both `GenServer` and `Commanded.Registration` macros.
While the code as written with handle_call/cast/info callbacks allowed for Registration.handle_info/2 to be called by sending the process a message, the other two handlers were not reachable.
By moving those two into the `__using__` block, we get what we're after.
Should resolve https://github.com/commanded/commanded-swarm-registry/issues/2
Big thanks to @predrag-rakic for finding, reporting and proposing the fix.

Allow registration handle_call/cast callbacks to be called
